# Generated by Django 3.0.5 on 2020-05-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tier'),
        ),
        migrations.DeleteModel(
            name='Tier',
        ),
    ]
