# Generated by Django 3.0.5 on 2020-05-04 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20200504_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=60, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
