# Generated by Django 3.0.5 on 2020-04-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_dbcommands'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DBCommands',
        ),
    ]
