# Generated by Django 3.0.5 on 2020-05-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_team_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='OMG', max_length=250, verbose_name='Название'),
        ),
    ]
