# Generated by Django 3.0.5 on 2020-05-05 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20200504_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameNow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(blank=True, max_length=3, null=True, verbose_name='формат')),
                ('starttime', models.DateTimeField(blank=True, null=True, verbose_name='Время игры')),
                ('predict', models.SmallIntegerField(blank=True, null=True, verbose_name='процент на победу первой команды')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_now', to='bot.Team', verbose_name='Команда 1')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_now', to='bot.Team', verbose_name='Команда 2')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Игра Сейчас',
                'verbose_name_plural': 'Игры Сейчас',
            },
        ),
    ]
