# Generated by Django 3.0.5 on 2020-04-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20200429_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='referral',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='BotUser'),
        ),
    ]
