# Generated by Django 3.0.6 on 2020-05-07 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_gamenow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тир')),
                ('value', models.FloatField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Коэфицент',
                'verbose_name_plural': 'Коэфиценты',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_bet_successful', models.IntegerField(default=0, verbose_name='количество успешных рискованных ставок')),
                ('risk_bet_all', models.IntegerField(default=0, verbose_name='всего количетсво рискованных ставок')),
                ('safe_bet_successful', models.IntegerField(default=0, verbose_name='количество успешных сейвовых ставок')),
                ('safe_bet_all', models.IntegerField(default=0, verbose_name='всего количетсво сейвовых ставок')),
                ('unpredictable_bet_successful', models.IntegerField(default=0, verbose_name='количество непредсказуемых рискованных ставок')),
                ('unpredictable_bet_all', models.IntegerField(default=0, verbose_name='всего непредсказуемых рискованных ставок')),
                ('all_bet_successful', models.IntegerField(default=0, verbose_name='количество успешных ставок всего')),
                ('bet_all', models.IntegerField(default=0, verbose_name='всего количетсво  ставок')),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тир')),
                ('coefficient', models.FloatField(blank=True, null=True, verbose_name='Коэфицент тира')),
            ],
            options={
                'verbose_name': 'Тир',
                'verbose_name_plural': 'Тиры',
            },
        ),
        migrations.AddField(
            model_name='botuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Админ ли?'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Tier'),
        ),
    ]
