# Generated by Django 3.0.6 on 2020-05-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20200508_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='coefficient',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Коэфицент тира'),
        ),
    ]
